# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'TwitterLBTA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterLBTA

  pod 'LBTAComponents' , '~> 0.1.9'
  platform :ios, '10.14.4'

end
