# Uncomment the next line to define a global platform for your project
# platform :ios, '12.2'

target 'Map' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Map
  pod 'SnapKit', '~> 5.0.0'
  pod 'lottie-ios'
  
end
