# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseCloudMessaging' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseCloudMessaging
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  target 'FirebaseCloudMessagingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseCloudMessagingUITests' do
    # Pods for testing
  end

end
