# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.2'
target 'Viper Geocode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'lottie-ios'

  # Pods for Viper Geocode

end
