# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cosmo City' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cosmo City
  
  platform :ios, '10.14.4'
  pod 'Alamofire', '~> 4.6'
  pod 'lottie-ios'
  
  # video player
  pod 'YoutubePlayer-in-WKWebView', '~> 0.2.0'

end
