# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

target 'Full Square' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Full Square
  pod 'SnapKit', '~> 5.0.0'
  pod 'lottie-ios'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

end
