# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.6'
  platform :ios, '10.14.4'
  pod 'MBProgressHUD', '~> 1.1.0'
  # Pods for Cep

end
